services:
  frontend-service:
    build: ./frontend
    image: frontend
    command: npm run dev
    container_name: frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/usr/src/app
